kind: pipeline
type: docker
name: master

steps:
  - name: prepare
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    commands:
      - yarn
      - yarn prepare

  - name: unit-test
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    commands:
      - yarn lint
      - yarn test

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
  event:
    - push
---
kind: pipeline
type: docker
name: pull request

steps:
  - name: prepare
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    commands:
      - yarn
      - yarn prepare

  - name: lint
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    commands:
      - yarn lint

  - name: unit-test
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    commands:
      - yarn test

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - feature/*
    - hotfix/*
  event:
    - push
    - pull_request
---
kind: pipeline
type: docker
name: release

steps:
  - name: prepare
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    commands:
      - yarn
      - yarn prepare

  - name: lint
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    commands:
      - yarn lint

  - name: unit-test
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    commands:
      - yarn test

  - name: publish
    image: 650139044964.dkr.ecr.us-east-1.amazonaws.com/resolve-docker
    pull: never
    environment:
      NPM_AUTH_TOKEN:
        from_secret: publish_npm_token
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_AUTH_TOKEN}" > ~/.npmrc
      - npm publish --access=public

volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - release*
  event:
    - push
