extends:
  - prettier
  - eslint:recommended
  - airbnb-base
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
env:
  es6: true
  node: true
  jest: true
rules:
  newline-per-chained-call: ['warn', { ignoreChainWithDepth: 2 } ]
  no-console: 'off'
  no-plusplus: 'off'
  no-param-reassign: ['error', { props: false }]
  no-restricted-syntax: ['off', 'ForInStatement', 'ForOfStatement']
  no-await-in-loop: 'off'
  class-methods-use-this: 'off'
  lines-between-class-members: 'off'
  semi: 'off'
  curly: ['error', 'all']
  linebreak-style: 'off'
  import/prefer-default-export: 'off'
  import/no-extraneous-dependencies: 'off'
  max-classes-per-file: 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: none
        requireLast: false
      singleline:
        delimiter: semi
        requireLast: false
