export { default as deleteMetricAlarm } from './deleteMetricAlarm'
export { default as getMetricData } from './getMetricData'
export { default as putMetricData } from './putMetricData'
export { default as putMetricAlarm } from './putMetricAlarm'
export { default as getOneMetricSummaryData } from './getOneMetricSummaryData'
export { default as listMetrics } from './listMetrics'
