export { default as describeLogStreams } from './describeLogStreams'
export { default as deleteLogGroup } from './deleteLogGroup'
export { default as filterLogEvents } from './filterLogEvents'
export { default as getLogsQueryResults } from './getLogsQueryResults'
export { setupRetentionLogs } from './setupRetentionLogs'
export { default as startLogsQuery } from './startLogsQuery'
