name: Feature CI/CD

on:
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: |
          yarn install --frozen-lock
          yarn audit
          yarn prepare

      - name: Lint
        run: yarn lint

      - name: Unit Tests
        run: yarn test

      - name: Functional Tests
        env:
          DEV_AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          DEV_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        run: yarn test:f
