name: Feature CI/CD

on:
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'

      - name: Build
        run: |
          yarn install --frozen-lock
          yarn audit
          yarn prepare

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
