name: Release CI/CD

on:
  push:
    branches:
      - release/**

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: |
          yarn
          yarn prepare

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Release
        run: |
          yarn
          yarn prepare
          npm publish --access=public
